### ISSUE TITLE
Modificación para integración continua

### ISSUE THREAD

**Issue by jeparca** [rafaeldrs/Recuento-Agora-US#3]
Descripción:
Esta incidencia es un cambio a realizar en la gestión de la construcción, de forma que incorpore la librería de verificación automáticamente en el repositorio maven que se use a la hora de compilar. Los cambios a realizar en el archivo pom.xml son los siguientes:

Sección repositories:

		<repository>
			<id>jeparca</id>
			<url>http://mvnrepo.jeparca.com:8080/repository/egcVerificacion</url>
		</repository>

Sección dependencies:

                 <dependency>
			<groupId>EGC</groupId>
			<artifactId>Verificacion</artifactId>
			<version>2.1.3</version>
		</dependency>

Esto incorporará automáticamente la librería.

**Comment by juanmtriguero** [comment]
https://github.com/rafaeldrs/Recuento-Agora-US/commit/eb05696ed25885d6d5eb630ed4bc20419d29bf75
